test:
  sf_media_browser:
    root_dir:           /tests-uploads

all:
  sf_media_browser:
    root_dir:               /uploads       # Browsable root directory relative to sf_web_dir
    thumbnails_enabled:     false          # Enable thumbnail creation on upload (requires sfThumnailPlugin)
    thumbnails_dir:         .thumbnails    # Directory name for storing thumbnails
    thumbnails_max_width:   64             # If thumbnails are enabled, you may define their size
    thumbnails_max_height:  64             
    assets_list:                           # Web assets used for the list template.
      js:                                  #   You may change this to use your own.
      #  - /sfMediaBrowserPlugin/js/list.js # You should disable this line if you use JQuery.
      # If you use jquery (not included so get jquery.js and jquery.dragndrop.js), enable these :                                    
      #  - /js/jquery.js                    # Core JQuery framework file.
      #  - /js/jquery.dragndrop.js          # This is presumed to be a bundle of jquery ui draggable and droppable.
      #  - /sfMediaBrowserPlugin/js/list.jquery.js # This included file is specific to sfMediaBrowser list template.
      css:
        - /sfMediaBrowserPlugin/css/list.css
    assets_widget:                          # Web assets for the form widget.
      js:
        - /sfMediaBrowserPlugin/js/WindowManager.js
        - /sfMediaBrowserPlugin/js/form_widget.js
      css:
        - /sfMediaBrowserPlugin/css/form_widget.css
    file_types:                           # define file_types is usefull for displaying icons in browser
      document:                           # type of file (also used as default icon name)
        extensions: [doc, xls, xcf, ai]   # extensions associated to this type
        icon:       doc                   # optional icon file name, without extension
      image:                              
        extensions: [png, jpg, jpeg, gif] 
      pdf:
        extensions: [pdf]
      bin:
        extensions: [bin, exe, sh, bat, deb, yum]
      video:
        extensions: [wmv, avi, mpg, mpeg, flv, mp4]
      audio:
        extensions: [ogg, mp3, flac, wma, cda]
      text:
        extensions: [txt]
      tarball:
        extensions: [tar, gz, zip, bzip, gzip, rar, 7z]
  sfImageTransformPlugin:       # see sfImageTransformPlugin for more info.
    mime_type:
      auto_detect: true
        
